### ISSUE TITLE
`master` --> `main`

### ISSUE THREAD

**Issue by jGaboardi** [oturns/geosnap#344]
Shall we take this pivotal moment in the history of `geosnap` to transition from a `master` to `main` branch?

**Comment by knaaptime** [comment]
i may have switched it already, but also changed your permissions. What can you do now?

**Comment by jGaboardi** [comment]
Nothing, I don't have a *Setting* tab.

<img width="1274" alt="Screenshot 2023-01-09 at 4 15 14 PM" src="https://user-images.githubusercontent.com/8590583/211409765-e2e04188-6e05-485b-9098-8ea7470fc76b.png">

**Comment by jGaboardi** [comment]
But it's not critical that I have admin access anyway.

**Comment by jGaboardi** [comment]
Completed by @knaaptime.
