### ISSUE TITLE
update links after org switch

### ISSUE THREAD

**Issue by jGaboardi** [oturns/geosnap#345]
We need to comb there everything and update the links following the organization change.
* [x] README
* [x] docs/conf
* [x] docs/index
* [x] docs/installation
* [x] tools/gitcount.ipynb
* [x] setup.py

**Comment by knaaptime** [comment]
i think the whole commviz file needs to be removed anyway

**Comment by knaaptime** [comment]
the quilt urls will remain unchanged

**Comment by knaaptime** [comment]
i think i've caught them all, but reopen if we find a lingering culprit
