### ISSUE TITLE
update infrastructure

### ISSUE THREAD

**Issue by knaaptime** [oturns/geosnap#354]
- versioneer --> setuptools_scm 
- setup.py --> pyproj.toml
- new testing "matrix"
- pre commit hooks and stuff?

**Comment by jGaboardi** [comment]
All good to close or should we keep open for the [coverage weirdness](https://github.com/oturns/geosnap/pull/350#issuecomment-1743953666)?

**Comment by knaaptime** [comment]
lets consider it solved for now. If it becomes an issue again we can revisit. I think this is resolved. I've never done the pre-commit hooks since i tend to blacken everything locally (and ive seen the precommit stuff go haywire on occasion) but feel free to open a PR if you're interested
