### ISSUE TITLE
User guide link is broken on user docs

### ISSUE THREAD

**Issue by sjsrey** [oturns/geosnap#366]
https://oturns.github.io/geosnap-guide/

**Comment by knaaptime** [comment]
I working on getting the new guide built and it should be updated shortly. Until then, two good resources are the [API docs](https://oturns.github.io/geosnap/api.html), and the [last workshop](https://github.com/knaaptime/pysal-narsc22/tree/main/content) taught with geosnap

**Comment by knaaptime** [comment]
the new guide has been published
