### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by jfhawkin** [oturns/geosnap#368]
geosnap\analyze\dynamics.py uses 
```for i, cluster in gdf[cluster_col].astype(int).iteritems():``` at line 345. 

This seems to be a simple deprecation fix. Change it to 
```for i, cluster in gdf[cluster_col].astype(int).items():``` 
based on https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.Series.iteritems.html

**Comment by knaaptime** [comment]
nice, thanks

**Comment by knaaptime** [comment]
resolved in v.0.12.0
